namespace UmaBlobber.MasterData;

/// <summary>
/// Built-in fallback when <c>master.mdb</c> is unavailable.
/// Regenerate via <c>Tools/ExportFallback</c> before releases.
/// </summary>
internal static class EmbeddedMasterFallback
{
    public static void Apply(GameMasterCatalog catalog)
    {
        catalog.MergeSection(MasterTextCategory.CharaShortName, CharaShortNames);
        catalog.MergeSkillEntries(Skills);
        catalog.SetTeamTrialsRawScores(TeamTrialsRawScores);
    }

    #region Embedded fallback dictionaries

    private static readonly Dictionary<int, string> CharaShortNames = new()
    {
        { 1001, "Special Week" },
        { 1002, "Silence Suzuka" },
        { 1003, "Tokai Teio" },
        { 1004, "Maruzensky" },
        { 1005, "Fuji Kiseki" },
        { 1006, "Oguri Cap" },
        { 1007, "Gold Ship" },
        { 1008, "Vodka" },
        { 1009, "Daiwa Scarlet" },
        { 1010, "Taiki Shuttle" },
        { 1011, "Grass Wonder" },
        { 1012, "Hishi Amazon" },
        { 1013, "Mejiro McQueen" },
        { 1014, "El Condor Pasa" },
        { 1015, "T.M. Opera O" },
        { 1016, "Narita Brian" },
        { 1017, "Symboli Rudolf" },
        { 1018, "Air Groove" },
        { 1019, "Agnes Digital" },
        { 1020, "Seiun Sky" },
        { 1021, "Tamamo Cross" },
        { 1022, "Fine Motion" },
        { 1023, "Biwa Hayahide" },
        { 1024, "Mayano Top Gun" },
        { 1025, "Manhattan Cafe" },
        { 1026, "Mihono Bourbon" },
        { 1027, "Mejiro Ryan" },
        { 1028, "Hishi Akebono" },
        { 1029, "Yukino Bijin" },
        { 1030, "Rice Shower" },
        { 1031, "Ines Fujin" },
        { 1032, "Agnes Tachyon" },
        { 1033, "Admire Vega" },
        { 1034, "Inari One" },
        { 1035, "Winning Ticket" },
        { 1036, "Air Shakur" },
        { 1037, "Eishin Flash" },
        { 1038, "Curren Chan" },
        { 1039, "Kawakami Princess" },
        { 1040, "Gold City" },
        { 1041, "Sakura Bakushin O" },
        { 1042, "Seeking the Pearl" },
        { 1043, "Shinko Windy" },
        { 1044, "Sweep Tosho" },
        { 1045, "Super Creek" },
        { 1046, "Smart Falcon" },
        { 1047, "Zenno Rob Roy" },
        { 1048, "Tosen Jordan" },
        { 1049, "Nakayama Festa" },
        { 1050, "Narita Taishin" },
        { 1051, "Nishino Flower" },
        { 1052, "Haru Urara" },
        { 1053, "Bamboo Memory" },
        { 1054, "Biko Pegasus" },
        { 1055, "Marvelous Sunday" },
        { 1056, "Matikanefukukitaru" },
        { 1057, "Mr. C.B." },
        { 1058, "Meisho Doto" },
        { 1059, "Mejiro Dober" },
        { 1060, "Nice Nature" },
        { 1061, "King Halo" },
        { 1062, "Matikanetannhauser" },
        { 1063, "Ikuno Dictus" },
        { 1064, "Mejiro Palmer" },
        { 1065, "Daitaku Helios" },
        { 1066, "Twin Turbo" },
        { 1067, "Satono Diamond" },
        { 1068, "Kitasan Black" },
        { 1069, "Sakura Chiyono O" },
        { 1070, "Sirius Symboli" },
        { 1071, "Mejiro Ardan" },
        { 1072, "Yaeno Muteki" },
        { 1073, "Tsurumaru Tsuyoshi" },
        { 1074, "Mejiro Bright" },
        { 1077, "Narita Top Road" },
        { 1078, "Yamanin Zephyr" },
        { 2001, "Happy Meek" },
        { 2002, "Bitter Glasse" },
        { 2003, "Little Cocon" },
        { 2004, "Montjeu" },
        { 9001, "Tazuna Hayakawa" },
        { 9002, "Director Akikawa" },
        { 9003, "Etsuko Otonashi" },
        { 9004, "Trainer Kiryuin" },
        { 9005, "Sasami Anshinzawa" },
        { 9006, "Riko Kashimoto" },
    };

    private static readonly Dictionary<int, SkillMasterEntry> Skills = new()
    {
        { 10071, new SkillMasterEntry("Warning Shot!", SkillActivateLotKind.Unconditional) },
        { 10081, new SkillMasterEntry("Xceleration", SkillActivateLotKind.Unconditional) },
        { 10091, new SkillMasterEntry("Red Ace", SkillActivateLotKind.Unconditional) },
        { 10111, new SkillMasterEntry("Focused Mind", SkillActivateLotKind.Unconditional) },
        { 10141, new SkillMasterEntry("Corazón ☆ Ardiente", SkillActivateLotKind.Unconditional) },
        { 10181, new SkillMasterEntry("Empress's Pride", SkillActivateLotKind.Unconditional) },
        { 10241, new SkillMasterEntry("1st Place Kiss☆", SkillActivateLotKind.Unconditional) },
        { 10271, new SkillMasterEntry("Feel the Burn!", SkillActivateLotKind.Unconditional) },
        { 10321, new SkillMasterEntry("Introduction to Physiology", SkillActivateLotKind.Unconditional) },
        { 10351, new SkillMasterEntry("V Is for Victory!", SkillActivateLotKind.Unconditional) },
        { 10411, new SkillMasterEntry("Class Rep + Speed = Bakushin", SkillActivateLotKind.Unconditional) },
        { 10451, new SkillMasterEntry("Clear Heart", SkillActivateLotKind.Unconditional) },
        { 10521, new SkillMasterEntry("Super-Duper Stoked", SkillActivateLotKind.Unconditional) },
        { 10561, new SkillMasterEntry("Luck Be with Me!", SkillActivateLotKind.Unconditional) },
        { 10601, new SkillMasterEntry("I Can Win Sometimes, Right?", SkillActivateLotKind.Unconditional) },
        { 10611, new SkillMasterEntry("Call Me King", SkillActivateLotKind.Unconditional) },
        { 10621, new SkillMasterEntry("Ready, Go!", SkillActivateLotKind.Unconditional) },
        { 100011, new SkillMasterEntry("Shooting Star", SkillActivateLotKind.Unconditional) },
        { 100021, new SkillMasterEntry("The View from the Lead Is Mine!", SkillActivateLotKind.Unconditional) },
        { 100031, new SkillMasterEntry("Sky-High Teio Step", SkillActivateLotKind.Unconditional) },
        { 100041, new SkillMasterEntry("Red Shift/LP1211-M", SkillActivateLotKind.Unconditional) },
        { 100051, new SkillMasterEntry("Lights of Vaudeville", SkillActivateLotKind.Unconditional) },
        { 100061, new SkillMasterEntry("Triumphant Pulse", SkillActivateLotKind.Unconditional) },
        { 100071, new SkillMasterEntry("Anchors Aweigh!", SkillActivateLotKind.Unconditional) },
        { 100081, new SkillMasterEntry("Cut and Drive!", SkillActivateLotKind.Unconditional) },
        { 100091, new SkillMasterEntry("Resplendent Red Ace", SkillActivateLotKind.Unconditional) },
        { 100101, new SkillMasterEntry("Shooting for Victory!", SkillActivateLotKind.Unconditional) },
        { 100111, new SkillMasterEntry("Where There's a Will, There's a Way", SkillActivateLotKind.Unconditional) },
        { 100121, new SkillMasterEntry("You and Me! One-on-One!", SkillActivateLotKind.Unconditional) },
        { 100131, new SkillMasterEntry("The Duty of Dignity Calls", SkillActivateLotKind.Unconditional) },
        { 100141, new SkillMasterEntry("Victoria por plancha ☆", SkillActivateLotKind.Unconditional) },
        { 100151, new SkillMasterEntry("This Dance Is for Vittoria!", SkillActivateLotKind.Unconditional) },
        { 100161, new SkillMasterEntry("Shadow Break", SkillActivateLotKind.Unconditional) },
        { 100171, new SkillMasterEntry("Behold Thine Emperor's Divine Might", SkillActivateLotKind.Unconditional) },
        { 100181, new SkillMasterEntry("Blazing Pride", SkillActivateLotKind.Unconditional) },
        { 100191, new SkillMasterEntry("OMG! (ﾟ∀ﾟ)  The Final Sprint! ☆", SkillActivateLotKind.Unconditional) },
        { 100201, new SkillMasterEntry("Angling and Scheming", SkillActivateLotKind.Unconditional) },
        { 100211, new SkillMasterEntry("White Lightning Comin' Through!", SkillActivateLotKind.Unconditional) },
        { 100221, new SkillMasterEntry("Fairy Tale", SkillActivateLotKind.Unconditional) },
        { 100231, new SkillMasterEntry("∴win Q.E.D.", SkillActivateLotKind.Unconditional) },
        { 100241, new SkillMasterEntry("Flashy☆Landing", SkillActivateLotKind.Unconditional) },
        { 100251, new SkillMasterEntry("Chasing After You", SkillActivateLotKind.Unconditional) },
        { 100261, new SkillMasterEntry("G00 1st. F∞;", SkillActivateLotKind.Unconditional) },
        { 100271, new SkillMasterEntry("Let's Pump Some Iron!", SkillActivateLotKind.Unconditional) },
        { 100281, new SkillMasterEntry("YUMMY☆SPEED!", SkillActivateLotKind.Unconditional) },
        { 100301, new SkillMasterEntry("Blue Rose Closer", SkillActivateLotKind.Unconditional) },
        { 100311, new SkillMasterEntry("All Charged! It's Go Time!", SkillActivateLotKind.Unconditional) },
        { 100321, new SkillMasterEntry("U=ma2", SkillActivateLotKind.Unconditional) },
        { 100331, new SkillMasterEntry("Shooting Star of Dioskouroi", SkillActivateLotKind.Unconditional) },
        { 100341, new SkillMasterEntry("Now We're Cruisin'!", SkillActivateLotKind.Unconditional) },
        { 100351, new SkillMasterEntry("Our Ticket to Win!", SkillActivateLotKind.Unconditional) },
        { 100371, new SkillMasterEntry("Schwarzes Schwert", SkillActivateLotKind.Unconditional) },
        { 100381, new SkillMasterEntry("#LookatCurren", SkillActivateLotKind.Unconditional) },
        { 100391, new SkillMasterEntry("A Princess Must Seize Victory!", SkillActivateLotKind.Unconditional) },
        { 100401, new SkillMasterEntry("KEEP IT REAL.", SkillActivateLotKind.Unconditional) },
        { 100411, new SkillMasterEntry("Genius x Bakushin = Victory", SkillActivateLotKind.Unconditional) },
        { 100441, new SkillMasterEntry("Victory Belongs to Me—Strelitzia! ☆", SkillActivateLotKind.Unconditional) },
        { 100451, new SkillMasterEntry("Pure Heart", SkillActivateLotKind.Unconditional) },
        { 100461, new SkillMasterEntry("SPARKLY☆STARDOM", SkillActivateLotKind.Unconditional) },
        { 100481, new SkillMasterEntry("Pop & Polish", SkillActivateLotKind.Unconditional) },
        { 100501, new SkillMasterEntry("Nemesis", SkillActivateLotKind.Unconditional) },
        { 100511, new SkillMasterEntry("Budding Blossom", SkillActivateLotKind.Unconditional) },
        { 100521, new SkillMasterEntry("Super-Duper Climax", SkillActivateLotKind.Unconditional) },
        { 100561, new SkillMasterEntry("I See Victory in My Future!", SkillActivateLotKind.Unconditional) },
        { 100581, new SkillMasterEntry("I Never Goof Up!", SkillActivateLotKind.Unconditional) },
        { 100591, new SkillMasterEntry("Moving Past, and Beyond", SkillActivateLotKind.Unconditional) },
        { 100601, new SkillMasterEntry("Just a Little Farther!", SkillActivateLotKind.Unconditional) },
        { 100611, new SkillMasterEntry("Prideful King", SkillActivateLotKind.Unconditional) },
        { 100621, new SkillMasterEntry("Go, Go, Mun!", SkillActivateLotKind.Unconditional) },
        { 100641, new SkillMasterEntry("Keep Pushing Ahead", SkillActivateLotKind.Unconditional) },
        { 100671, new SkillMasterEntry("Eternal Encompassing Shine", SkillActivateLotKind.Unconditional) },
        { 100681, new SkillMasterEntry("Victory Cheer!", SkillActivateLotKind.Unconditional) },
        { 100691, new SkillMasterEntry("Ambition to Surpass the Sakura", SkillActivateLotKind.Unconditional) },
        { 100711, new SkillMasterEntry("A Lifelong Dream, A Moment's Flight", SkillActivateLotKind.Unconditional) },
        { 100721, new SkillMasterEntry("Peerless Dance of Flowering Flames", SkillActivateLotKind.Unconditional) },
        { 100741, new SkillMasterEntry("Lovely Spring Breeze", SkillActivateLotKind.Unconditional) },
        { 110011, new SkillMasterEntry("Dazzl'n ♪ Diver", SkillActivateLotKind.Unconditional) },
        { 110031, new SkillMasterEntry("Certain Victory", SkillActivateLotKind.Unconditional) },
        { 110041, new SkillMasterEntry("A Kiss for Courage", SkillActivateLotKind.Unconditional) },
        { 110051, new SkillMasterEntry("Ravissant", SkillActivateLotKind.Unconditional) },
        { 110061, new SkillMasterEntry("Festive Miracle", SkillActivateLotKind.Unconditional) },
        { 110111, new SkillMasterEntry("Superior Heal", SkillActivateLotKind.Unconditional) },
        { 110131, new SkillMasterEntry("Legacy of the Strong", SkillActivateLotKind.Unconditional) },
        { 110141, new SkillMasterEntry("Condor's Fury", SkillActivateLotKind.Unconditional) },
        { 110151, new SkillMasterEntry("Barcarole of Blessings", SkillActivateLotKind.Unconditional) },
        { 110171, new SkillMasterEntry("Arrows Whistle, Shadows Disperse", SkillActivateLotKind.Unconditional) },
        { 110181, new SkillMasterEntry("Eternal Moments", SkillActivateLotKind.Unconditional) },
        { 110201, new SkillMasterEntry("Break It Down!", SkillActivateLotKind.Unconditional) },
        { 110221, new SkillMasterEntry("Best Day Ever", SkillActivateLotKind.Unconditional) },
        { 110231, new SkillMasterEntry("Presents from X", SkillActivateLotKind.Unconditional) },
        { 110241, new SkillMasterEntry("Flowery☆Maneuver", SkillActivateLotKind.Unconditional) },
        { 110261, new SkillMasterEntry("Operation Cacao", SkillActivateLotKind.Unconditional) },
        { 110301, new SkillMasterEntry("Every Rose Has Its Fangs", SkillActivateLotKind.Unconditional) },
        { 110371, new SkillMasterEntry("Guten Appetit ♪", SkillActivateLotKind.Unconditional) },
        { 110381, new SkillMasterEntry("One True Color", SkillActivateLotKind.Unconditional) },
        { 110401, new SkillMasterEntry("Dancing in the Leaves", SkillActivateLotKind.Unconditional) },
        { 110451, new SkillMasterEntry("Give Mummy a Hug ♡", SkillActivateLotKind.Unconditional) },
        { 110521, new SkillMasterEntry("114th Time's the Charm", SkillActivateLotKind.Unconditional) },
        { 110561, new SkillMasterEntry("Bountiful Harvest", SkillActivateLotKind.Unconditional) },
        { 110601, new SkillMasterEntry("Go☆Go☆Goal!", SkillActivateLotKind.Unconditional) },
        { 110611, new SkillMasterEntry("Louder! Tracen Cheer!", SkillActivateLotKind.Unconditional) },
        { 200011, new SkillMasterEntry("Right-Handed ◎", SkillActivateLotKind.Unconditional) },
        { 200012, new SkillMasterEntry("Right-Handed ○", SkillActivateLotKind.Unconditional) },
        { 200013, new SkillMasterEntry("Right-Handed ×", SkillActivateLotKind.Unconditional) },
        { 200014, new SkillMasterEntry("Right-Handed Demon", SkillActivateLotKind.Unconditional) },
        { 200021, new SkillMasterEntry("Left-Handed ◎", SkillActivateLotKind.Unconditional) },
        { 200022, new SkillMasterEntry("Left-Handed ○", SkillActivateLotKind.Unconditional) },
        { 200023, new SkillMasterEntry("Left-Handed ×", SkillActivateLotKind.Unconditional) },
        { 200031, new SkillMasterEntry("Tokyo Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200032, new SkillMasterEntry("Tokyo Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200033, new SkillMasterEntry("Tokyo Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200041, new SkillMasterEntry("Nakayama Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200042, new SkillMasterEntry("Nakayama Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200043, new SkillMasterEntry("Nakayama Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200051, new SkillMasterEntry("Hanshin Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200052, new SkillMasterEntry("Hanshin Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200053, new SkillMasterEntry("Hanshin Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200061, new SkillMasterEntry("Kyoto Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200062, new SkillMasterEntry("Kyoto Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200063, new SkillMasterEntry("Kyoto Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200064, new SkillMasterEntry("Yodo Invicta", SkillActivateLotKind.Unconditional) },
        { 200071, new SkillMasterEntry("Chukyo Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200072, new SkillMasterEntry("Chukyo Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200073, new SkillMasterEntry("Chukyo Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200081, new SkillMasterEntry("Sapporo Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200082, new SkillMasterEntry("Sapporo Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200083, new SkillMasterEntry("Sapporo Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200091, new SkillMasterEntry("Hakodate Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200092, new SkillMasterEntry("Hakodate Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200093, new SkillMasterEntry("Hakodate Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200101, new SkillMasterEntry("Fukushima Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200102, new SkillMasterEntry("Fukushima Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200103, new SkillMasterEntry("Fukushima Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200111, new SkillMasterEntry("Niigata Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200112, new SkillMasterEntry("Niigata Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200113, new SkillMasterEntry("Niigata Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200121, new SkillMasterEntry("Kokura Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200122, new SkillMasterEntry("Kokura Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200123, new SkillMasterEntry("Kokura Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200131, new SkillMasterEntry("Standard Distance ◎", SkillActivateLotKind.Unconditional) },
        { 200132, new SkillMasterEntry("Standard Distance ○", SkillActivateLotKind.Unconditional) },
        { 200133, new SkillMasterEntry("Standard Distance ×", SkillActivateLotKind.Unconditional) },
        { 200141, new SkillMasterEntry("Non-Standard Distance ◎", SkillActivateLotKind.Unconditional) },
        { 200142, new SkillMasterEntry("Non-Standard Distance ○", SkillActivateLotKind.Unconditional) },
        { 200143, new SkillMasterEntry("Non-Standard Distance ×", SkillActivateLotKind.Unconditional) },
        { 200151, new SkillMasterEntry("Firm Conditions ◎", SkillActivateLotKind.Unconditional) },
        { 200152, new SkillMasterEntry("Firm Conditions ○", SkillActivateLotKind.Unconditional) },
        { 200153, new SkillMasterEntry("Firm Conditions ×", SkillActivateLotKind.Unconditional) },
        { 200154, new SkillMasterEntry("Firm Course Menace", SkillActivateLotKind.Unconditional) },
        { 200161, new SkillMasterEntry("Wet Conditions ◎", SkillActivateLotKind.Unconditional) },
        { 200162, new SkillMasterEntry("Wet Conditions ○", SkillActivateLotKind.Unconditional) },
        { 200163, new SkillMasterEntry("Wet Conditions ×", SkillActivateLotKind.Unconditional) },
        { 200171, new SkillMasterEntry("Spring Runner ◎", SkillActivateLotKind.Unconditional) },
        { 200172, new SkillMasterEntry("Spring Runner ○", SkillActivateLotKind.Unconditional) },
        { 200173, new SkillMasterEntry("Spring Runner ×", SkillActivateLotKind.Unconditional) },
        { 200174, new SkillMasterEntry("Spring Spectacle", SkillActivateLotKind.Unconditional) },
        { 200181, new SkillMasterEntry("Summer Runner ◎", SkillActivateLotKind.Unconditional) },
        { 200182, new SkillMasterEntry("Summer Runner ○", SkillActivateLotKind.Unconditional) },
        { 200183, new SkillMasterEntry("Summer Runner ×", SkillActivateLotKind.Unconditional) },
        { 200191, new SkillMasterEntry("Fall Runner ◎", SkillActivateLotKind.Unconditional) },
        { 200192, new SkillMasterEntry("Fall Runner ○", SkillActivateLotKind.Unconditional) },
        { 200193, new SkillMasterEntry("Fall Runner ×", SkillActivateLotKind.Unconditional) },
        { 200194, new SkillMasterEntry("Fall Frenzy", SkillActivateLotKind.Unconditional) },
        { 200201, new SkillMasterEntry("Winter Runner ◎", SkillActivateLotKind.Unconditional) },
        { 200202, new SkillMasterEntry("Winter Runner ○", SkillActivateLotKind.Unconditional) },
        { 200203, new SkillMasterEntry("Winter Runner ×", SkillActivateLotKind.Unconditional) },
        { 200211, new SkillMasterEntry("Sunny Days ◎", SkillActivateLotKind.Unconditional) },
        { 200212, new SkillMasterEntry("Sunny Days ○", SkillActivateLotKind.Unconditional) },
        { 200221, new SkillMasterEntry("Cloudy Days ◎", SkillActivateLotKind.Unconditional) },
        { 200222, new SkillMasterEntry("Cloudy Days ○", SkillActivateLotKind.Unconditional) },
        { 200231, new SkillMasterEntry("Rainy Days ◎", SkillActivateLotKind.Unconditional) },
        { 200232, new SkillMasterEntry("Rainy Days ○", SkillActivateLotKind.Unconditional) },
        { 200233, new SkillMasterEntry("Rainy Days ×", SkillActivateLotKind.Unconditional) },
        { 200241, new SkillMasterEntry("Snowy Days ◎", SkillActivateLotKind.Unconditional) },
        { 200242, new SkillMasterEntry("Snowy Days ○", SkillActivateLotKind.Unconditional) },
        { 200251, new SkillMasterEntry("Inner Post Proficiency ◎", SkillActivateLotKind.Unconditional) },
        { 200252, new SkillMasterEntry("Inner Post Proficiency ○", SkillActivateLotKind.Unconditional) },
        { 200253, new SkillMasterEntry("Inner Post Averseness", SkillActivateLotKind.Unconditional) },
        { 200261, new SkillMasterEntry("Outer Post Proficiency ◎", SkillActivateLotKind.Unconditional) },
        { 200262, new SkillMasterEntry("Outer Post Proficiency ○", SkillActivateLotKind.Unconditional) },
        { 200263, new SkillMasterEntry("Outer Post Averseness", SkillActivateLotKind.Unconditional) },
        { 200271, new SkillMasterEntry("Maverick ◎", SkillActivateLotKind.Unconditional) },
        { 200272, new SkillMasterEntry("Maverick ○", SkillActivateLotKind.Unconditional) },
        { 200281, new SkillMasterEntry("Competitive Spirit ◎", SkillActivateLotKind.Unconditional) },
        { 200282, new SkillMasterEntry("Competitive Spirit ○", SkillActivateLotKind.Unconditional) },
        { 200283, new SkillMasterEntry("Wallflower", SkillActivateLotKind.Unconditional) },
        { 200291, new SkillMasterEntry("Target in Sight ◎", SkillActivateLotKind.Unconditional) },
        { 200292, new SkillMasterEntry("Target in Sight ○", SkillActivateLotKind.Unconditional) },
        { 200301, new SkillMasterEntry("Long Shot ◎", SkillActivateLotKind.Unconditional) },
        { 200302, new SkillMasterEntry("Long Shot ○", SkillActivateLotKind.Unconditional) },
        { 200311, new SkillMasterEntry("G1 Averseness", SkillActivateLotKind.Unconditional) },
        { 200321, new SkillMasterEntry("Paddock Fright", SkillActivateLotKind.Unconditional) },
        { 200331, new SkillMasterEntry("Professor of Curvature", SkillActivateLotKind.Wit) },
        { 200332, new SkillMasterEntry("Corner Adept ○", SkillActivateLotKind.Wit) },
        { 200333, new SkillMasterEntry("Corner Adept ×", SkillActivateLotKind.Wit) },
        { 200341, new SkillMasterEntry("Corner Connoisseur", SkillActivateLotKind.Wit) },
        { 200342, new SkillMasterEntry("Corner Acceleration ○", SkillActivateLotKind.Wit) },
        { 200343, new SkillMasterEntry("Corner Acceleration ×", SkillActivateLotKind.Wit) },
        { 200351, new SkillMasterEntry("Swinging Maestro", SkillActivateLotKind.Wit) },
        { 200352, new SkillMasterEntry("Corner Recovery ○", SkillActivateLotKind.Wit) },
        { 200353, new SkillMasterEntry("Corner Recovery ×", SkillActivateLotKind.Wit) },
        { 200361, new SkillMasterEntry("Beeline Burst", SkillActivateLotKind.Wit) },
        { 200362, new SkillMasterEntry("Straightaway Adept", SkillActivateLotKind.Wit) },
        { 200371, new SkillMasterEntry("Rushing Gale!", SkillActivateLotKind.Wit) },
        { 200372, new SkillMasterEntry("Straightaway Acceleration", SkillActivateLotKind.Wit) },
        { 200381, new SkillMasterEntry("Breath of Fresh Air", SkillActivateLotKind.Wit) },
        { 200382, new SkillMasterEntry("Straightaway Recovery", SkillActivateLotKind.Wit) },
        { 200391, new SkillMasterEntry("Ramp Revulsion", SkillActivateLotKind.Wit) },
        { 200401, new SkillMasterEntry("Packphobia", SkillActivateLotKind.Wit) },
        { 200411, new SkillMasterEntry("Defeatist", SkillActivateLotKind.Wit) },
        { 200421, new SkillMasterEntry("Reckless", SkillActivateLotKind.Wit) },
        { 200431, new SkillMasterEntry("Concentration", SkillActivateLotKind.Wit) },
        { 200432, new SkillMasterEntry("Focus", SkillActivateLotKind.Wit) },
        { 200433, new SkillMasterEntry("Gatekept", SkillActivateLotKind.Wit) },
        { 200441, new SkillMasterEntry("Iron Will", SkillActivateLotKind.Wit) },
        { 200442, new SkillMasterEntry("Lay Low", SkillActivateLotKind.Wit) },
        { 200451, new SkillMasterEntry("Center Stage", SkillActivateLotKind.Wit) },
        { 200452, new SkillMasterEntry("Prudent Positioning", SkillActivateLotKind.Wit) },
        { 200461, new SkillMasterEntry("It's On!", SkillActivateLotKind.Wit) },
        { 200462, new SkillMasterEntry("Ramp Up", SkillActivateLotKind.Wit) },
        { 200471, new SkillMasterEntry("Indomitable", SkillActivateLotKind.Wit) },
        { 200472, new SkillMasterEntry("Pace Strategy", SkillActivateLotKind.Wit) },
        { 200481, new SkillMasterEntry("Unruffled", SkillActivateLotKind.Wit) },
        { 200482, new SkillMasterEntry("Calm in a Crowd", SkillActivateLotKind.Wit) },
        { 200491, new SkillMasterEntry("No Stopping Me!", SkillActivateLotKind.Wit) },
        { 200492, new SkillMasterEntry("Nimble Navigator", SkillActivateLotKind.Wit) },
        { 200501, new SkillMasterEntry("Lane Legerdemain", SkillActivateLotKind.Wit) },
        { 200502, new SkillMasterEntry("Go with the Flow", SkillActivateLotKind.Wit) },
        { 200511, new SkillMasterEntry("In Body and Mind", SkillActivateLotKind.Wit) },
        { 200512, new SkillMasterEntry("Homestretch Haste", SkillActivateLotKind.Wit) },
        { 200521, new SkillMasterEntry("Running Idle", SkillActivateLotKind.Wit) },
        { 200531, new SkillMasterEntry("Taking the Lead", SkillActivateLotKind.Wit) },
        { 200532, new SkillMasterEntry("Early Lead", SkillActivateLotKind.Wit) },
        { 200541, new SkillMasterEntry("Escape Artist", SkillActivateLotKind.Wit) },
        { 200542, new SkillMasterEntry("Fast-Paced", SkillActivateLotKind.Wit) },
        { 200551, new SkillMasterEntry("Unrestrained", SkillActivateLotKind.Wit) },
        { 200552, new SkillMasterEntry("Final Push", SkillActivateLotKind.Wit) },
        { 200561, new SkillMasterEntry("Calm and Collected", SkillActivateLotKind.Wit) },
        { 200562, new SkillMasterEntry("Stamina to Spare", SkillActivateLotKind.Wit) },
        { 200571, new SkillMasterEntry("Race Planner", SkillActivateLotKind.Wit) },
        { 200572, new SkillMasterEntry("Preferred Position", SkillActivateLotKind.Wit) },
        { 200581, new SkillMasterEntry("Speed Star", SkillActivateLotKind.Wit) },
        { 200582, new SkillMasterEntry("Prepared to Pass", SkillActivateLotKind.Wit) },
        { 200591, new SkillMasterEntry("Fast & Furious", SkillActivateLotKind.Wit) },
        { 200592, new SkillMasterEntry("Position Pilfer", SkillActivateLotKind.Wit) },
        { 200601, new SkillMasterEntry("On Your Left!", SkillActivateLotKind.Wit) },
        { 200602, new SkillMasterEntry("Slick Surge", SkillActivateLotKind.Wit) },
        { 200611, new SkillMasterEntry("Rising Dragon", SkillActivateLotKind.Wit) },
        { 200612, new SkillMasterEntry("Outer Swell", SkillActivateLotKind.Wit) },
        { 200621, new SkillMasterEntry("Sleeping Lion", SkillActivateLotKind.Wit) },
        { 200622, new SkillMasterEntry("Standing By", SkillActivateLotKind.Wit) },
        { 200631, new SkillMasterEntry("Sturm und Drang", SkillActivateLotKind.Wit) },
        { 200632, new SkillMasterEntry("Masterful Gambit", SkillActivateLotKind.Wit) },
        { 200641, new SkillMasterEntry("Encroaching Shadow", SkillActivateLotKind.Wit) },
        { 200642, new SkillMasterEntry("Straightaway Spurt", SkillActivateLotKind.Wit) },
        { 200651, new SkillMasterEntry("Turbo Sprint", SkillActivateLotKind.Wit) },
        { 200652, new SkillMasterEntry("Sprinting Gear", SkillActivateLotKind.Wit) },
        { 200662, new SkillMasterEntry("Wait-and-See", SkillActivateLotKind.Wit) },
        { 200671, new SkillMasterEntry("Blinding Flash", SkillActivateLotKind.Wit) },
        { 200672, new SkillMasterEntry("Gap Closer", SkillActivateLotKind.Wit) },
        { 200681, new SkillMasterEntry("Mile Maven", SkillActivateLotKind.Wit) },
        { 200682, new SkillMasterEntry("Productive Plan", SkillActivateLotKind.Wit) },
        { 200691, new SkillMasterEntry("Keen Eye", SkillActivateLotKind.Wit) },
        { 200692, new SkillMasterEntry("Watchful Eye", SkillActivateLotKind.Wit) },
        { 200701, new SkillMasterEntry("Furious Feat", SkillActivateLotKind.Wit) },
        { 200702, new SkillMasterEntry("Updrafters", SkillActivateLotKind.Wit) },
        { 200711, new SkillMasterEntry("Trackblazer", SkillActivateLotKind.Wit) },
        { 200712, new SkillMasterEntry("Rosy Outlook", SkillActivateLotKind.Wit) },
        { 200721, new SkillMasterEntry("Killer Tunes", SkillActivateLotKind.Wit) },
        { 200722, new SkillMasterEntry("Up-Tempo", SkillActivateLotKind.Wit) },
        { 200731, new SkillMasterEntry("Unyielding", SkillActivateLotKind.Wit) },
        { 200732, new SkillMasterEntry("Steadfast", SkillActivateLotKind.Wit) },
        { 200741, new SkillMasterEntry("Cooldown", SkillActivateLotKind.Wit) },
        { 200742, new SkillMasterEntry("Deep Breaths", SkillActivateLotKind.Wit) },
        { 200751, new SkillMasterEntry("Innate Experience", SkillActivateLotKind.Wit) },
        { 200752, new SkillMasterEntry("Inside Scoop", SkillActivateLotKind.Wit) },
        { 200761, new SkillMasterEntry("Adrenaline Rush", SkillActivateLotKind.Wit) },
        { 200762, new SkillMasterEntry("Extra Tank", SkillActivateLotKind.Wit) },
        { 200771, new SkillMasterEntry("Trick (Front)", SkillActivateLotKind.Wit) },
        { 200772, new SkillMasterEntry("Tantalizing Trick", SkillActivateLotKind.Wit) },
        { 200781, new SkillMasterEntry("Trick (Rear)", SkillActivateLotKind.Wit) },
        { 200791, new SkillMasterEntry("Frenzied Front Runners", SkillActivateLotKind.Wit) },
        { 200801, new SkillMasterEntry("Frenzied Pace Chasers", SkillActivateLotKind.Wit) },
        { 200811, new SkillMasterEntry("Frenzied Late Surgers", SkillActivateLotKind.Wit) },
        { 200821, new SkillMasterEntry("Frenzied End Closers", SkillActivateLotKind.Wit) },
        { 200831, new SkillMasterEntry("Subdued Front Runners", SkillActivateLotKind.Wit) },
        { 200841, new SkillMasterEntry("Flustered Front Runners", SkillActivateLotKind.Wit) },
        { 200851, new SkillMasterEntry("Hesitant Front Runners", SkillActivateLotKind.Wit) },
        { 200861, new SkillMasterEntry("Subdued Pace Chasers", SkillActivateLotKind.Wit) },
        { 200871, new SkillMasterEntry("Flustered Pace Chasers", SkillActivateLotKind.Wit) },
        { 200881, new SkillMasterEntry("Hesitant Pace Chasers", SkillActivateLotKind.Wit) },
        { 200891, new SkillMasterEntry("Subdued Late Surgers", SkillActivateLotKind.Wit) },
        { 200901, new SkillMasterEntry("Flustered Late Surgers", SkillActivateLotKind.Wit) },
        { 200911, new SkillMasterEntry("Hesitant Late Surgers", SkillActivateLotKind.Wit) },
        { 200921, new SkillMasterEntry("Subdued End Closers", SkillActivateLotKind.Wit) },
        { 200931, new SkillMasterEntry("Flustered End Closers", SkillActivateLotKind.Wit) },
        { 200941, new SkillMasterEntry("Hesitant End Closers", SkillActivateLotKind.Wit) },
        { 200951, new SkillMasterEntry("Oi Racecourse ◎", SkillActivateLotKind.Unconditional) },
        { 200952, new SkillMasterEntry("Oi Racecourse ○", SkillActivateLotKind.Unconditional) },
        { 200953, new SkillMasterEntry("Oi Racecourse ×", SkillActivateLotKind.Unconditional) },
        { 200961, new SkillMasterEntry("Sprint Straightaways ◎", SkillActivateLotKind.Wit) },
        { 200962, new SkillMasterEntry("Sprint Straightaways ○", SkillActivateLotKind.Wit) },
        { 200971, new SkillMasterEntry("Sprint Corners ◎", SkillActivateLotKind.Wit) },
        { 200972, new SkillMasterEntry("Sprint Corners ○", SkillActivateLotKind.Wit) },
        { 200981, new SkillMasterEntry("Staggering Lead", SkillActivateLotKind.Wit) },
        { 200982, new SkillMasterEntry("Huge Lead", SkillActivateLotKind.Wit) },
        { 200991, new SkillMasterEntry("Plan X", SkillActivateLotKind.Wit) },
        { 200992, new SkillMasterEntry("Countermeasure", SkillActivateLotKind.Wit) },
        { 201001, new SkillMasterEntry("Perfect Prep!", SkillActivateLotKind.Wit) },
        { 201002, new SkillMasterEntry("Meticulous Measures", SkillActivateLotKind.Wit) },
        { 201011, new SkillMasterEntry("Adored by All", SkillActivateLotKind.Wit) },
        { 201012, new SkillMasterEntry("Intimidate", SkillActivateLotKind.Wit) },
        { 201021, new SkillMasterEntry("You've Got No Shot", SkillActivateLotKind.Wit) },
        { 201022, new SkillMasterEntry("Stop Right There!", SkillActivateLotKind.Wit) },
        { 201031, new SkillMasterEntry("Mile Straightaways ◎", SkillActivateLotKind.Wit) },
        { 201032, new SkillMasterEntry("Mile Straightaways ○", SkillActivateLotKind.Wit) },
        { 201041, new SkillMasterEntry("Mile Corners ◎", SkillActivateLotKind.Wit) },
        { 201042, new SkillMasterEntry("Mile Corners ○", SkillActivateLotKind.Wit) },
        { 201051, new SkillMasterEntry("Changing Gears", SkillActivateLotKind.Wit) },
        { 201052, new SkillMasterEntry("Shifting Gears", SkillActivateLotKind.Wit) },
        { 201061, new SkillMasterEntry("Step on the Gas!", SkillActivateLotKind.Wit) },
        { 201062, new SkillMasterEntry("Acceleration", SkillActivateLotKind.Wit) },
        { 201071, new SkillMasterEntry("Big-Sisterly", SkillActivateLotKind.Wit) },
        { 201072, new SkillMasterEntry("Unyielding Spirit", SkillActivateLotKind.Wit) },
        { 201081, new SkillMasterEntry("Greed for Speed", SkillActivateLotKind.Wit) },
        { 201082, new SkillMasterEntry("Speed Eater", SkillActivateLotKind.Wit) },
        { 201091, new SkillMasterEntry("Battle Formation", SkillActivateLotKind.Wit) },
        { 201092, new SkillMasterEntry("Opening Gambit", SkillActivateLotKind.Wit) },
        { 201101, new SkillMasterEntry("Medium Straightaways ◎", SkillActivateLotKind.Wit) },
        { 201102, new SkillMasterEntry("Medium Straightaways ○", SkillActivateLotKind.Wit) },
        { 201103, new SkillMasterEntry("Flash Forward", SkillActivateLotKind.Wit) },
        { 201111, new SkillMasterEntry("Medium Corners ◎", SkillActivateLotKind.Wit) },
        { 201112, new SkillMasterEntry("Medium Corners ○", SkillActivateLotKind.Wit) },
        { 201121, new SkillMasterEntry("Clairvoyance", SkillActivateLotKind.Wit) },
        { 201122, new SkillMasterEntry("Hawkeye", SkillActivateLotKind.Wit) },
        { 201131, new SkillMasterEntry("Lightning Step", SkillActivateLotKind.Wit) },
        { 201132, new SkillMasterEntry("Thunderbolt Step", SkillActivateLotKind.Wit) },
        { 201141, new SkillMasterEntry("Miraculous Step", SkillActivateLotKind.Wit) },
        { 201142, new SkillMasterEntry("Soft Step", SkillActivateLotKind.Wit) },
        { 201151, new SkillMasterEntry("Dominator", SkillActivateLotKind.Wit) },
        { 201152, new SkillMasterEntry("Tether", SkillActivateLotKind.Wit) },
        { 201161, new SkillMasterEntry("Mystifying Murmur", SkillActivateLotKind.Wit) },
        { 201162, new SkillMasterEntry("Murmur", SkillActivateLotKind.Wit) },
        { 201171, new SkillMasterEntry("Long Straightaways ◎", SkillActivateLotKind.Wit) },
        { 201172, new SkillMasterEntry("Long Straightaways ○", SkillActivateLotKind.Wit) },
        { 201173, new SkillMasterEntry("Blast Forward", SkillActivateLotKind.Wit) },
        { 201181, new SkillMasterEntry("Long Corners ◎", SkillActivateLotKind.Wit) },
        { 201182, new SkillMasterEntry("Long Corners ○", SkillActivateLotKind.Wit) },
        { 201191, new SkillMasterEntry("Vanguard Spirit", SkillActivateLotKind.Wit) },
        { 201192, new SkillMasterEntry("Keeping the Lead", SkillActivateLotKind.Wit) },
        { 201201, new SkillMasterEntry("VIP Pass", SkillActivateLotKind.Wit) },
        { 201202, new SkillMasterEntry("Passing Pro", SkillActivateLotKind.Wit) },
        { 201211, new SkillMasterEntry("Overwhelming Pressure", SkillActivateLotKind.Wit) },
        { 201212, new SkillMasterEntry("Pressure", SkillActivateLotKind.Wit) },
        { 201221, new SkillMasterEntry("Stamina Siphon", SkillActivateLotKind.Wit) },
        { 201222, new SkillMasterEntry("Stamina Eater", SkillActivateLotKind.Wit) },
        { 201231, new SkillMasterEntry("Illusionist", SkillActivateLotKind.Wit) },
        { 201232, new SkillMasterEntry("Smoke Screen", SkillActivateLotKind.Wit) },
        { 201241, new SkillMasterEntry("Front Runner Straightaways ◎", SkillActivateLotKind.Wit) },
        { 201242, new SkillMasterEntry("Front Runner Straightaways ○", SkillActivateLotKind.Wit) },
        { 201251, new SkillMasterEntry("Front Runner Corners ◎", SkillActivateLotKind.Wit) },
        { 201252, new SkillMasterEntry("Front Runner Corners ○", SkillActivateLotKind.Wit) },
        { 201261, new SkillMasterEntry("Sixth Sense", SkillActivateLotKind.Wit) },
        { 201262, new SkillMasterEntry("Dodging Danger", SkillActivateLotKind.Wit) },
        { 201271, new SkillMasterEntry("Top Runner", SkillActivateLotKind.Wit) },
        { 201272, new SkillMasterEntry("Leader's Pride", SkillActivateLotKind.Wit) },
        { 201281, new SkillMasterEntry("Restless", SkillActivateLotKind.Wit) },
        { 201282, new SkillMasterEntry("Moxie", SkillActivateLotKind.Wit) },
        { 201291, new SkillMasterEntry("Reignition", SkillActivateLotKind.Wit) },
        { 201292, new SkillMasterEntry("Second Wind", SkillActivateLotKind.Wit) },
        { 201302, new SkillMasterEntry("Restart", SkillActivateLotKind.Wit) },
        { 201311, new SkillMasterEntry("Pace Chaser Straightaways ◎", SkillActivateLotKind.Wit) },
        { 201312, new SkillMasterEntry("Pace Chaser Straightaways ○", SkillActivateLotKind.Wit) },
        { 201321, new SkillMasterEntry("Pace Chaser Corners ◎", SkillActivateLotKind.Wit) },
        { 201322, new SkillMasterEntry("Pace Chaser Corners ○", SkillActivateLotKind.Wit) },
        { 201331, new SkillMasterEntry("Technician", SkillActivateLotKind.Wit) },
        { 201332, new SkillMasterEntry("Shrewd Step", SkillActivateLotKind.Wit) },
        { 201341, new SkillMasterEntry("Determined Descent", SkillActivateLotKind.Wit) },
        { 201342, new SkillMasterEntry("Straight Descent", SkillActivateLotKind.Wit) },
        { 201351, new SkillMasterEntry("Gourmand", SkillActivateLotKind.Wit) },
        { 201352, new SkillMasterEntry("Hydrate", SkillActivateLotKind.Wit) },
        { 201361, new SkillMasterEntry("Shatterproof", SkillActivateLotKind.Wit) },
        { 201362, new SkillMasterEntry("Tactical Tweak", SkillActivateLotKind.Wit) },
        { 201371, new SkillMasterEntry("Dazzling Disorientation", SkillActivateLotKind.Wit) },
        { 201372, new SkillMasterEntry("Disorient", SkillActivateLotKind.Wit) },
        { 201381, new SkillMasterEntry("Late Surger Straightaways ◎", SkillActivateLotKind.Wit) },
        { 201382, new SkillMasterEntry("Late Surger Straightaways ○", SkillActivateLotKind.Wit) },
        { 201391, new SkillMasterEntry("Late Surger Corners ◎", SkillActivateLotKind.Wit) },
        { 201392, new SkillMasterEntry("Late Surger Corners ○", SkillActivateLotKind.Wit) },
        { 201401, new SkillMasterEntry("Hard Worker", SkillActivateLotKind.Wit) },
        { 201402, new SkillMasterEntry("Fighter", SkillActivateLotKind.Wit) },
        { 201411, new SkillMasterEntry("15,000,000 CC", SkillActivateLotKind.Wit) },
        { 201412, new SkillMasterEntry("1,500,000 CC", SkillActivateLotKind.Wit) },
        { 201421, new SkillMasterEntry("Relax", SkillActivateLotKind.Wit) },
        { 201422, new SkillMasterEntry("A Small Breather", SkillActivateLotKind.Wit) },
        { 201431, new SkillMasterEntry("The Bigger Picture", SkillActivateLotKind.Wit) },
        { 201432, new SkillMasterEntry("Studious", SkillActivateLotKind.Wit) },
        { 201441, new SkillMasterEntry("All-Seeing Eyes", SkillActivateLotKind.Wit) },
        { 201442, new SkillMasterEntry("Sharp Gaze", SkillActivateLotKind.Wit) },
        { 201451, new SkillMasterEntry("End Closer Straightaways ◎", SkillActivateLotKind.Wit) },
        { 201452, new SkillMasterEntry("End Closer Straightaways ○", SkillActivateLotKind.Wit) },
        { 201461, new SkillMasterEntry("End Closer Corners ◎", SkillActivateLotKind.Wit) },
        { 201462, new SkillMasterEntry("End Closer Corners ○", SkillActivateLotKind.Wit) },
        { 201471, new SkillMasterEntry("The Coast Is Clear!", SkillActivateLotKind.Wit) },
        { 201472, new SkillMasterEntry("I Can See Right Through You", SkillActivateLotKind.Wit) },
        { 201481, new SkillMasterEntry("Go-Home Specialist", SkillActivateLotKind.Wit) },
        { 201482, new SkillMasterEntry("After-School Stroll", SkillActivateLotKind.Wit) },
        { 201491, new SkillMasterEntry("Serenity", SkillActivateLotKind.Wit) },
        { 201492, new SkillMasterEntry("Levelheaded", SkillActivateLotKind.Wit) },
        { 201501, new SkillMasterEntry("Crusader", SkillActivateLotKind.Wit) },
        { 201502, new SkillMasterEntry("Strategist", SkillActivateLotKind.Wit) },
        { 201511, new SkillMasterEntry("Petrifying Gaze", SkillActivateLotKind.Wit) },
        { 201512, new SkillMasterEntry("Intense Gaze", SkillActivateLotKind.Wit) },
        { 201521, new SkillMasterEntry("Front Runner Savvy ◎", SkillActivateLotKind.Unconditional) },
        { 201522, new SkillMasterEntry("Front Runner Savvy ○", SkillActivateLotKind.Unconditional) },
        { 201531, new SkillMasterEntry("Pace Chaser Savvy ◎", SkillActivateLotKind.Unconditional) },
        { 201532, new SkillMasterEntry("Pace Chaser Savvy ○", SkillActivateLotKind.Unconditional) },
        { 201541, new SkillMasterEntry("Late Surger Savvy ◎", SkillActivateLotKind.Unconditional) },
        { 201542, new SkillMasterEntry("Late Surger Savvy ○", SkillActivateLotKind.Unconditional) },
        { 201551, new SkillMasterEntry("End Closer Savvy ◎", SkillActivateLotKind.Unconditional) },
        { 201552, new SkillMasterEntry("End Closer Savvy ○", SkillActivateLotKind.Unconditional) },
        { 201561, new SkillMasterEntry("Super Lucky Seven", SkillActivateLotKind.Wit) },
        { 201562, new SkillMasterEntry("Lucky Seven", SkillActivateLotKind.Wit) },
        { 201571, new SkillMasterEntry("Triple 7s", SkillActivateLotKind.Wit) },
        { 201581, new SkillMasterEntry("Highlander", SkillActivateLotKind.Wit) },
        { 201591, new SkillMasterEntry("Uma Stan", SkillActivateLotKind.Wit) },
        { 201592, new SkillMasterEntry("Superstan", SkillActivateLotKind.Wit) },
        { 201601, new SkillMasterEntry("Groundwork", SkillActivateLotKind.Wit) },
        { 201611, new SkillMasterEntry("Tail Held High", SkillActivateLotKind.Wit) },
        { 201612, new SkillMasterEntry("Tail Nine", SkillActivateLotKind.Wit) },
        { 201621, new SkillMasterEntry("Shake It Out", SkillActivateLotKind.Wit) },
        { 201631, new SkillMasterEntry("Sympathy", SkillActivateLotKind.Unconditional) },
        { 201641, new SkillMasterEntry("Lone Wolf", SkillActivateLotKind.Unconditional) },
        { 201651, new SkillMasterEntry("Slipstream", SkillActivateLotKind.Wit) },
        { 201661, new SkillMasterEntry("Playtime's Over!", SkillActivateLotKind.Wit) },
        { 201662, new SkillMasterEntry("See Ya Later!", SkillActivateLotKind.Wit) },
        { 201671, new SkillMasterEntry("Trending in the Charts!", SkillActivateLotKind.Wit) },
        { 201672, new SkillMasterEntry("Top Pick", SkillActivateLotKind.Wit) },
        { 201681, new SkillMasterEntry("Lead the Charge!", SkillActivateLotKind.Wit) },
        { 201682, new SkillMasterEntry("Forward, March!", SkillActivateLotKind.Wit) },
        { 201691, new SkillMasterEntry("Lie in Wait", SkillActivateLotKind.Wit) },
        { 201692, new SkillMasterEntry("Be Still", SkillActivateLotKind.Wit) },
        { 201701, new SkillMasterEntry("Come What May", SkillActivateLotKind.Wit) },
        { 201702, new SkillMasterEntry("All I've Got", SkillActivateLotKind.Wit) },
        { 201801, new SkillMasterEntry("♡ 3D Nail Art", SkillActivateLotKind.Unconditional) },
        { 201901, new SkillMasterEntry("Neck and Neck", SkillActivateLotKind.Wit) },
        { 201902, new SkillMasterEntry("Head-On", SkillActivateLotKind.Wit) },
        { 202001, new SkillMasterEntry("Master of the Sands", SkillActivateLotKind.Wit) },
        { 202002, new SkillMasterEntry("Familiar Ground", SkillActivateLotKind.Wit) },
        { 202011, new SkillMasterEntry("Headliner", SkillActivateLotKind.Wit) },
        { 202012, new SkillMasterEntry("Feature Act", SkillActivateLotKind.Wit) },
        { 202021, new SkillMasterEntry("Daring Strike", SkillActivateLotKind.Wit) },
        { 202022, new SkillMasterEntry("Early Start", SkillActivateLotKind.Wit) },
        { 202031, new SkillMasterEntry("Nothing Ventured", SkillActivateLotKind.Wit) },
        { 202032, new SkillMasterEntry("Risky Business", SkillActivateLotKind.Wit) },
        { 202041, new SkillMasterEntry("In High Spirits", SkillActivateLotKind.Wit) },
        { 202042, new SkillMasterEntry("Light as a Feather", SkillActivateLotKind.Wit) },
        { 202051, new SkillMasterEntry("Runaway", SkillActivateLotKind.Unconditional) },
        { 202061, new SkillMasterEntry("Best in Japan", SkillActivateLotKind.Wit) },
        { 202071, new SkillMasterEntry("Of Calm Mind", SkillActivateLotKind.Wit) },
        { 202072, new SkillMasterEntry("Free-Spirited", SkillActivateLotKind.Wit) },
        { 202081, new SkillMasterEntry("From the Brink", SkillActivateLotKind.Wit) },
        { 202082, new SkillMasterEntry("Take the Chance", SkillActivateLotKind.Wit) },
        { 202091, new SkillMasterEntry("Burning Soul", SkillActivateLotKind.Wit) },
        { 202092, new SkillMasterEntry("Fighting Spirit", SkillActivateLotKind.Wit) },
        { 202101, new SkillMasterEntry("Elated", SkillActivateLotKind.Wit) },
        { 202102, new SkillMasterEntry("Eager", SkillActivateLotKind.Wit) },
        { 202111, new SkillMasterEntry("Full of Vigor", SkillActivateLotKind.Wit) },
        { 202112, new SkillMasterEntry("Pumped", SkillActivateLotKind.Wit) },
        { 202121, new SkillMasterEntry("Dauntless", SkillActivateLotKind.Wit) },
        { 202122, new SkillMasterEntry("Fearless", SkillActivateLotKind.Wit) },
        { 202131, new SkillMasterEntry("Wild Wind", SkillActivateLotKind.Wit) },
        { 202132, new SkillMasterEntry("With All My Soul", SkillActivateLotKind.Wit) },
        { 202141, new SkillMasterEntry("You're Not the Boss of Me!", SkillActivateLotKind.Unconditional) },
        { 202151, new SkillMasterEntry("Keep Going!", SkillActivateLotKind.Wit) },
        { 202152, new SkillMasterEntry("Full Throttle", SkillActivateLotKind.Wit) },
        { 202161, new SkillMasterEntry("Restraint", SkillActivateLotKind.Unconditional) },
        { 210011, new SkillMasterEntry("Burning Spirit SPD", SkillActivateLotKind.Wit) },
        { 210012, new SkillMasterEntry("Ignited Spirit SPD", SkillActivateLotKind.Wit) },
        { 210021, new SkillMasterEntry("Burning Spirit STA", SkillActivateLotKind.Wit) },
        { 210022, new SkillMasterEntry("Ignited Spirit STA", SkillActivateLotKind.Wit) },
        { 210031, new SkillMasterEntry("Burning Spirit PWR", SkillActivateLotKind.Wit) },
        { 210032, new SkillMasterEntry("Ignited Spirit PWR", SkillActivateLotKind.Wit) },
        { 210041, new SkillMasterEntry("Burning Spirit GUTS", SkillActivateLotKind.Wit) },
        { 210042, new SkillMasterEntry("Ignited Spirit GUTS", SkillActivateLotKind.Wit) },
        { 210051, new SkillMasterEntry("Burning Spirit WIT", SkillActivateLotKind.Wit) },
        { 210052, new SkillMasterEntry("Ignited Spirit WIT", SkillActivateLotKind.Wit) },
        { 210061, new SkillMasterEntry("Radiant Star", SkillActivateLotKind.Wit) },
        { 210062, new SkillMasterEntry("Glittering Star", SkillActivateLotKind.Wit) },
        { 300011, new SkillMasterEntry("Unquenched Thirst", SkillActivateLotKind.Unconditional) },
        { 300021, new SkillMasterEntry("Unchanging", SkillActivateLotKind.Unconditional) },
        { 300031, new SkillMasterEntry("Towards the Scenery I Seek", SkillActivateLotKind.Unconditional) },
        { 300041, new SkillMasterEntry("Creeping Anxiety", SkillActivateLotKind.Unconditional) },
        { 300051, new SkillMasterEntry("Blatant Fear", SkillActivateLotKind.Unconditional) },
        { 300061, new SkillMasterEntry("Dream Run", SkillActivateLotKind.Unconditional) },
        { 300071, new SkillMasterEntry("Show Me What Lies Beyond!", SkillActivateLotKind.Unconditional) },
        { 300081, new SkillMasterEntry("Hoiya! Have a Good Run!", SkillActivateLotKind.Unconditional) },
        { 300091, new SkillMasterEntry("As a Friend and Rival", SkillActivateLotKind.Unconditional) },
        { 300101, new SkillMasterEntry("Cheers of a Fellow Dreamer", SkillActivateLotKind.Unconditional) },
        { 300111, new SkillMasterEntry("Chin Up, Derby Umamusume!", SkillActivateLotKind.Unconditional) },
        { 300121, new SkillMasterEntry("For the Team", SkillActivateLotKind.Unconditional) },
        { 900011, new SkillMasterEntry("Shooting Star", SkillActivateLotKind.Wit) },
        { 900021, new SkillMasterEntry("The View from the Lead Is Mine!", SkillActivateLotKind.Wit) },
        { 900031, new SkillMasterEntry("Sky-High Teio Step", SkillActivateLotKind.Wit) },
        { 900041, new SkillMasterEntry("Red Shift/LP1211-M", SkillActivateLotKind.Wit) },
        { 900051, new SkillMasterEntry("Lights of Vaudeville", SkillActivateLotKind.Wit) },
        { 900061, new SkillMasterEntry("Triumphant Pulse", SkillActivateLotKind.Wit) },
        { 900071, new SkillMasterEntry("Anchors Aweigh!", SkillActivateLotKind.Wit) },
        { 900081, new SkillMasterEntry("Cut and Drive!", SkillActivateLotKind.Wit) },
        { 900091, new SkillMasterEntry("Resplendent Red Ace", SkillActivateLotKind.Wit) },
        { 900101, new SkillMasterEntry("Shooting for Victory!", SkillActivateLotKind.Wit) },
        { 900111, new SkillMasterEntry("Where There's a Will, There's a Way", SkillActivateLotKind.Wit) },
        { 900121, new SkillMasterEntry("You and Me! One-on-One!", SkillActivateLotKind.Wit) },
        { 900131, new SkillMasterEntry("The Duty of Dignity Calls", SkillActivateLotKind.Wit) },
        { 900141, new SkillMasterEntry("Victoria por plancha ☆", SkillActivateLotKind.Wit) },
        { 900151, new SkillMasterEntry("This Dance Is for Vittoria!", SkillActivateLotKind.Wit) },
        { 900161, new SkillMasterEntry("Shadow Break", SkillActivateLotKind.Wit) },
        { 900171, new SkillMasterEntry("Behold Thine Emperor's Divine Might", SkillActivateLotKind.Wit) },
        { 900181, new SkillMasterEntry("Blazing Pride", SkillActivateLotKind.Wit) },
        { 900191, new SkillMasterEntry("OMG! (ﾟ∀ﾟ)  The Final Sprint! ☆", SkillActivateLotKind.Wit) },
        { 900201, new SkillMasterEntry("Angling and Scheming", SkillActivateLotKind.Wit) },
        { 900211, new SkillMasterEntry("White Lightning Comin' Through!", SkillActivateLotKind.Wit) },
        { 900221, new SkillMasterEntry("Fairy Tale", SkillActivateLotKind.Wit) },
        { 900231, new SkillMasterEntry("∴win Q.E.D.", SkillActivateLotKind.Wit) },
        { 900241, new SkillMasterEntry("Flashy☆Landing", SkillActivateLotKind.Wit) },
        { 900251, new SkillMasterEntry("Chasing After You", SkillActivateLotKind.Wit) },
        { 900261, new SkillMasterEntry("G00 1st. F∞;", SkillActivateLotKind.Wit) },
        { 900271, new SkillMasterEntry("Let's Pump Some Iron!", SkillActivateLotKind.Wit) },
        { 900281, new SkillMasterEntry("YUMMY☆SPEED!", SkillActivateLotKind.Wit) },
        { 900301, new SkillMasterEntry("Blue Rose Closer", SkillActivateLotKind.Wit) },
        { 900311, new SkillMasterEntry("All Charged! It's Go Time!", SkillActivateLotKind.Wit) },
        { 900321, new SkillMasterEntry("U=ma2", SkillActivateLotKind.Wit) },
        { 900331, new SkillMasterEntry("Shooting Star of Dioskouroi", SkillActivateLotKind.Wit) },
        { 900341, new SkillMasterEntry("Now We're Cruisin'!", SkillActivateLotKind.Wit) },
        { 900351, new SkillMasterEntry("Our Ticket to Win!", SkillActivateLotKind.Wit) },
        { 900371, new SkillMasterEntry("Schwarzes Schwert", SkillActivateLotKind.Wit) },
        { 900381, new SkillMasterEntry("#LookatCurren", SkillActivateLotKind.Wit) },
        { 900391, new SkillMasterEntry("A Princess Must Seize Victory!", SkillActivateLotKind.Wit) },
        { 900401, new SkillMasterEntry("KEEP IT REAL.", SkillActivateLotKind.Wit) },
        { 900411, new SkillMasterEntry("Genius x Bakushin = Victory", SkillActivateLotKind.Wit) },
        { 900441, new SkillMasterEntry("Victory Belongs to Me—Strelitzia! ☆", SkillActivateLotKind.Wit) },
        { 900451, new SkillMasterEntry("Pure Heart", SkillActivateLotKind.Wit) },
        { 900461, new SkillMasterEntry("SPARKLY☆STARDOM", SkillActivateLotKind.Wit) },
        { 900481, new SkillMasterEntry("Pop & Polish", SkillActivateLotKind.Wit) },
        { 900501, new SkillMasterEntry("Nemesis", SkillActivateLotKind.Wit) },
        { 900511, new SkillMasterEntry("Budding Blossom", SkillActivateLotKind.Wit) },
        { 900521, new SkillMasterEntry("Super-Duper Climax", SkillActivateLotKind.Wit) },
        { 900561, new SkillMasterEntry("I See Victory in My Future!", SkillActivateLotKind.Wit) },
        { 900581, new SkillMasterEntry("I Never Goof Up!", SkillActivateLotKind.Wit) },
        { 900591, new SkillMasterEntry("Moving Past, and Beyond", SkillActivateLotKind.Wit) },
        { 900601, new SkillMasterEntry("Just a Little Farther!", SkillActivateLotKind.Wit) },
        { 900611, new SkillMasterEntry("Prideful King", SkillActivateLotKind.Wit) },
        { 900621, new SkillMasterEntry("Go, Go, Mun!", SkillActivateLotKind.Wit) },
        { 900641, new SkillMasterEntry("Keep Pushing Ahead", SkillActivateLotKind.Wit) },
        { 900671, new SkillMasterEntry("Eternal Encompassing Shine", SkillActivateLotKind.Wit) },
        { 900681, new SkillMasterEntry("Victory Cheer!", SkillActivateLotKind.Wit) },
        { 900691, new SkillMasterEntry("Ambition to Surpass the Sakura", SkillActivateLotKind.Wit) },
        { 900711, new SkillMasterEntry("A Lifelong Dream, A Moment's Flight", SkillActivateLotKind.Wit) },
        { 900721, new SkillMasterEntry("Peerless Dance of Flowering Flames", SkillActivateLotKind.Wit) },
        { 900741, new SkillMasterEntry("Lovely Spring Breeze", SkillActivateLotKind.Wit) },
        { 910011, new SkillMasterEntry("Dazzl'n ♪ Diver", SkillActivateLotKind.Wit) },
        { 910031, new SkillMasterEntry("Certain Victory", SkillActivateLotKind.Wit) },
        { 910041, new SkillMasterEntry("A Kiss for Courage", SkillActivateLotKind.Wit) },
        { 910051, new SkillMasterEntry("Ravissant", SkillActivateLotKind.Wit) },
        { 910061, new SkillMasterEntry("Festive Miracle", SkillActivateLotKind.Wit) },
        { 910111, new SkillMasterEntry("Superior Heal", SkillActivateLotKind.Wit) },
        { 910131, new SkillMasterEntry("Legacy of the Strong", SkillActivateLotKind.Wit) },
        { 910141, new SkillMasterEntry("Condor's Fury", SkillActivateLotKind.Wit) },
        { 910151, new SkillMasterEntry("Barcarole of Blessings", SkillActivateLotKind.Wit) },
        { 910171, new SkillMasterEntry("Arrows Whistle, Shadows Disperse", SkillActivateLotKind.Wit) },
        { 910181, new SkillMasterEntry("Eternal Moments", SkillActivateLotKind.Wit) },
        { 910201, new SkillMasterEntry("Break It Down!", SkillActivateLotKind.Wit) },
        { 910221, new SkillMasterEntry("Best day ever", SkillActivateLotKind.Wit) },
        { 910231, new SkillMasterEntry("Presents from X", SkillActivateLotKind.Wit) },
        { 910241, new SkillMasterEntry("Flowery☆Maneuver", SkillActivateLotKind.Wit) },
        { 910261, new SkillMasterEntry("Operation Cacao", SkillActivateLotKind.Wit) },
        { 910301, new SkillMasterEntry("Every Rose Has Its Fangs", SkillActivateLotKind.Wit) },
        { 910371, new SkillMasterEntry("Guten Appetit ♪", SkillActivateLotKind.Wit) },
        { 910381, new SkillMasterEntry("One True Color", SkillActivateLotKind.Wit) },
        { 910401, new SkillMasterEntry("Dancing in the Leaves", SkillActivateLotKind.Wit) },
        { 910451, new SkillMasterEntry("Give Mummy a Hug ♡", SkillActivateLotKind.Wit) },
        { 910521, new SkillMasterEntry("114th Time's the Charm", SkillActivateLotKind.Wit) },
        { 910561, new SkillMasterEntry("Bountiful Harvest", SkillActivateLotKind.Wit) },
        { 910601, new SkillMasterEntry("Go☆Go☆Goal!", SkillActivateLotKind.Wit) },
        { 910611, new SkillMasterEntry("Louder! Tracen Cheer!", SkillActivateLotKind.Wit) },
        { 1000011, new SkillMasterEntry("Carnival Bonus", SkillActivateLotKind.Unconditional) },
        { 1000012, new SkillMasterEntry("Carnival Bonus", SkillActivateLotKind.Unconditional) },
        { 1100011, new SkillMasterEntry("Feelin' a Bit Silly", SkillActivateLotKind.Unconditional) },
    };

    /// <summary>
    /// Base score values from team_stadium_raw_score (id -> score).
    /// Populated from master.mdb via the ExportFallback tool (includes all entries).
    /// When empty, SkillRaceScoring falls back to the legacy 26-57 range for skill activation scores.
    /// Use catalog.GetTeamTrialsRawScoreValue(rawScoreId) for the canonical base amount
    /// (500 white, 1200 gold, variable for uniques depending on skill level + uma rarity).
    /// Names/descriptions available via MasterTextCategory.TeamTrialsScoreType (140) and TeamTrialsScoreDesc (141).
    /// </summary>
    private static readonly Dictionary<int, int> TeamTrialsRawScores = new()
    {
        // The full set (hundreds of score types) is generated by Tools/ExportFallback when a master.mdb is available.
        // Legacy/hardcoded range (26-57) continues to be used in SkillRaceScoring as a fallback when this is empty.
    };

    #endregion
}
