using System;
using System.Collections.Generic;
using System.Text;

namespace UmaBlobber.Data
{
    internal class DBData
    {
        /// <summary>
        /// Maps 4-digit character IDs to their names.
        /// </summary>
        static internal Dictionary<int, string> ShortNames = new() {
            { 1001, "Special Week" },
            { 1002, "Silence Suzuka" },
            { 1003, "Tokai Teio" },
            { 1004, "Maruzensky" },
            { 1005, "Fuji Kiseki" },
            { 1006, "Oguri Cap" },
            { 1007, "Gold Ship" },
            { 1008, "Vodka" },
            { 1009, "Daiwa Scarlet" },
            { 1010, "Taiki Shuttle" },
            { 1011, "Grass Wonder" },
            { 1012, "Hishi Amazon" },
            { 1013, "Mejiro McQueen" },
            { 1014, "El Condor Pasa" },
            { 1015, "T.M. Opera O" },
            { 1016, "Narita Brian" },
            { 1017, "Symboli Rudolf" },
            { 1018, "Air Groove" },
            { 1019, "Agnes Digital" },
            { 1020, "Seiun Sky" },
            { 1021, "Tamamo Cross" },
            { 1022, "Fine Motion" },
            { 1023, "Biwa Hayahide" },
            { 1024, "Mayano Top Gun" },
            { 1025, "Manhattan Cafe" },
            { 1026, "Mihono Bourbon" },
            { 1027, "Mejiro Ryan" },
            { 1028, "Hishi Akebono" },
            { 1029, "Yukino Bijin" },
            { 1030, "Rice Shower" },
            { 1031, "Ines Fujin" },
            { 1032, "Agnes Tachyon" },
            { 1033, "Admire Vega" },
            { 1034, "Inari One" },
            { 1035, "Winning Ticket" },
            { 1036, "Air Shakur" },
            { 1037, "Eishin Flash" },
            { 1038, "Curren Chan" },
            { 1039, "Kawakami Princess" },
            { 1040, "Gold City" },
            { 1041, "Sakura Bakushin O" },
            { 1042, "Seeking the Pearl" },
            { 1043, "Shinko Windy" },
            { 1044, "Sweep Tosho" },
            { 1045, "Super Creek" },
            { 1046, "Smart Falcon" },
            { 1047, "Zenno Rob Roy" },
            { 1048, "Tosen Jordan" },
            { 1049, "Nakayama Festa" },
            { 1050, "Narita Taishin" },
            { 1051, "Nishino Flower" },
            { 1052, "Haru Urara" },
            { 1053, "Bamboo Memory" },
            { 1054, "Biko Pegasus" },
            { 1055, "Marvelous Sunday" },
            { 1056, "Matikanefukukitaru" },
            { 1057, "Mr. C.B." },
            { 1058, "Meisho Doto" },
            { 1059, "Mejiro Dober" },
            { 1060, "Nice Nature" },
            { 1061, "King Halo" },
            { 1062, "Matikanetannhauser" },
            { 1063, "Ikuno Dictus" },
            { 1064, "Mejiro Palmer" },
            { 1065, "Daitaku Helios" },
            { 1066, "Twin Turbo" },
            { 1067, "Satono Diamond" },
            { 1068, "Kitasan Black" },
            { 1069, "Sakura Chiyono O" },
            { 1070, "Sirius Symboli" },
            { 1071, "Mejiro Ardan" },
            { 1072, "Yaeno Muteki" },
            { 1073, "Tsurumaru Tsuyoshi" },
            { 1074, "Mejiro Bright" },
            { 1077, "Narita Top Road" },
            { 1078, "Yamanin Zephyr" },
        };

        /// <summary>
        /// Maps card_ids to their full names, including variations.
        /// </summary>
        static internal Dictionary<int, string> FullNames = new() {
            { 100101, "[Special Dreamer] Special Week" },
            { 100102, "[Hopp'n♪Happy Heart] Special Week" },
            { 100103, "[Ruler of Japan] Special Week" },
            { 100201, "[Innocent Silence] Silence Suzuka" },
            { 100301, "[Peak Joy] Tokai Teio" },
            { 100302, "[Beyond the Horizon] Tokai Teio" },
            { 100401, "[Formula R] Maruzensky" },
            { 100402, "[Hot☆Summer Night] Maruzensky" },
            { 100501, "[Shooting Star Revue] Fuji Kiseki" },
            { 100502, "[Succès Étoilé] Fuji Kiseki" },
            { 100601, "[Starlight Beat] Oguri Cap" },
            { 100602, "[Ashen Miracle] Oguri Cap" },
            { 100701, "[Red Strife] Gold Ship" },
            { 100801, "[Wild Top Gear] Vodka" },
            { 100901, "[Peak Blue] Daiwa Scarlet" },
            { 101001, "[Wild Frontier] Taiki Shuttle" },
            { 101002, "[Bubblegum☆Memories] Taiki Shuttle" },
            { 101101, "[Stone-Piercing Blue] Grass Wonder" },
            { 101102, "[Saintly Jade Cleric] Grass Wonder" },
            { 101201, "[Azure Amazon] Hishi Amazon" },
            { 101301, "[Frontline Elegance] Mejiro McQueen" },
            { 101302, "[End of the Skies] Mejiro McQueen" },
            { 101401, "[El☆Número 1] El Condor Pasa" },
            { 101402, "[Kukulkan Warrior] El Condor Pasa" },
            { 101501, "[O Sole Suo!] T.M. Opera O" },
            { 101502, "[New Year, Same Radiance!] T.M. Opera O" },
            { 101601, "[Maverick] Narita Brian" },
            { 101701, "[Emperor's Path] Symboli Rudolf" },
            { 101702, "[Archer by Moonlight] Symboli Rudolf" },
            { 101801, "[Empress Road] Air Groove" },
            { 101802, "[Quercus Civilis] Air Groove" },
            { 101901, "[Full-Color Fangirling] Agnes Digital" },
            { 102001, "[Reeling in the Big One] Seiun Sky" },
            { 102002, "[Soirée des Chatons] Seiun Sky" },
            { 102101, "[Fast as Lightning] Tamamo Cross" },
            { 102201, "[Noble Seamair] Fine Motion" },
            { 102202, "[Titania] Fine Motion" },
            { 102301, "[pf. Winning Equation...] Biwa Hayahide" },
            { 102302, "[Rouge Caroler] Biwa Hayahide" },
            { 102401, "[Scramble☆Zone] Mayano Top Gun" },
            { 102402, "[Sunlight Bouquet] Mayano Top Gun" },
            { 102501, "[Creeping Shadow] Manhattan Cafe" },
            { 102601, "[MB-19890425] Mihono Bourbon" },
            { 102602, "[CODE: ICING] Mihono Bourbon" },
            { 102701, "[Down the Line] Mejiro Ryan" },
            { 102801, "[Buono ☆ Alla Moda] Hishi Akebono" },
            { 103001, "[Rosy Dreams] Rice Shower" },
            { 103002, "[Vampire Makeover!] Rice Shower" },
            { 103101, "[Always Electrifying] Ines Fujin" },
            { 103201, "[Tach-nology] Agnes Tachyon" },
            { 103301, "[Starry Nocturne] Admire Vega" },
            { 103401, "[Edomurasaki] Inari One" },
            { 103501, "[Get to Winning!] Winning Ticket" },
            { 103601, "[unsigned] Air Shakur" },
            { 103701, "[Meisterschaft] Eishin Flash" },
            { 103702, "[Precise Chocolatier] Eishin Flash" },
            { 103801, "[Fille Éclair] Curren Chan" },
            { 103802, "[Ma Chérie of the New Moon] Curren Chan" },
            { 103901, "[Princess of Pink] Kawakami Princess" },
            { 104001, "[Authentic / 1928] Gold City" },
            { 104002, "[Autumn Cosmos] Gold City" },
            { 104101, "[Blossom in Learning] Sakura Bakushin O" },
            { 104401, "[Platanus Witch] Sweep Tosho" },
            { 104501, "[Murmuring Stream] Super Creek" },
            { 104502, "[Chiffon-Wrapped Mummy] Super Creek" },
            { 104601, "[LOVE☆4EVER] Smart Falcon" },
            { 104801, "[Jokester ☆ Vibes] Tosen Jordan" },
            { 105001, "[Nevertheless] Narita Taishin" },
            { 105101, "[Layered Petals] Nishino Flower" },
            { 105201, "[Bestest Prize ♪] Haru Urara" },
            { 105202, "[New Year ♪ New Urara!] Haru Urara" },
            { 105601, "[Rising☆Fortune] Matikanefukukitaru" },
            { 105602, "[Lucky Tidings] Matikanefukukitaru" },
            { 105801, "[Turbulent Blue] Meisho Doto" },
            { 105901, "[Off the Line] Mejiro Dober" },
            { 105902, "[Sapphire Sojourn] Mejiro Dober" },
            { 106001, "[Poinsettia Ribbon] Nice Nature" },
            { 106002, "[Run & Win] Nice Nature" },
            { 106101, "[King of Emeralds] King Halo" },
            { 106102, "[Cheerleader in Noble White] King Halo" },
            { 106201, "[Clippety-Tippety-Clop] Matikanetannhauser" },
            { 106401, "[Line Breakthrough] Mejiro Palmer" },
            { 106701, "[Natural Brilliance] Satono Diamond" },
            { 106801, "[Gilded Shrine to Glory] Kitasan Black" },
            { 106901, "[Strength in Full Bloom] Sakura Chiyono O" },
            { 107101, "[Crystalline] Mejiro Ardan" },
            { 107201, "[Blazed Head, Covered Fists] Yaeno Muteki" },
            { 107401, "[Brunissage Line] Mejiro Bright" },
            { 9100101, "[Special Dreamer] Special Week" },
            { 9101101, "[Stone-Piercing Blue] Grass Wonder" }
        };

    }
}
